baseURL: https://armantopchu.netlify.app/
languageCode: en-us
title: Arman's Website for Data Analytics for Finance 
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      My name is Arman Topchu and I created this website using R for my Data Analytics for Finance assignment.
    title: Welcome to my website!
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Park Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: atopchu.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 000-0000 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Arman Topchu
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/EVEBITDA
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/arman.prive
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/armantopchu
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/armantopchu
  image: ''
  name: Arman Topchu
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Who am I?
        title: About me
        url: blogs/aboutme
      - image: pic02.jpg
        subtitle: It is fascinating how the majority of our life can fit only on one page!
        title: Preview my CV!
        url: blogs/preview-cv
      - image: pic03.jpg
        subtitle: Based on a true story
        title: A story about a little dog and his big dream
        url: blogs/flying-dog
      - image: pic04.jpg
        subtitle: Resources used in the process of creating this website
        title: Acknowledgements
        url: blogs/acknowledgements
      - image: pic05.jpg
        subtitle: 
        title: My all-time favorite movies!
        url: blogs/fav-movies
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: My all-time favorite series!
        url: blogs/fav-series
  two:
    buttonText: Arman's GitHub directory
    enable: yes
    subtitle: "Please feel free to use or inspect my code from my github public directory."
    title: Interested in recreating this website?
    url: blogs
