[build]
  publish = "public"
  command = "hugo"
  functions = "C:\\16. IA v1\\Development\\website_vF_2024_updated\\functions"

[build.environment]
  HUGO_VERSION = "0.88.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.88.1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.88.1"  