[build]
  command = "npm run build"
  publish = ".next"  # Should match the distDir in next.config.js

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  functions = "netlify/functions"  # The directory containing your serverless functions for local development

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
