[build]
  publish = "public"  # The directory to deploy (adjust based on your project)
  functions = "netlify/functions"  # The directory containing your serverless functions
  command = "bash ./scripts/build.sh"  # The build command

[[plugins]]
  package = "@netlify/plugin-nextjs"  # Add this if you're using Next.js, adjust as needed

[dev]
  functions = "netlify/functions"  # The directory containing your serverless functions for local development

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
