[build]
  command = "npm run build"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-nextjs" #because we are using Next-js

[dev]
  functions = "netlify/functions"  # The directory containing your serverless functions for local development

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
