[build]
  publish = "public"  # The directory to deploy (adjust based on your project)
  functions = "netlify/functions"  # The directory containing your serverless functions
  command = "bash ./scripts/build.sh"  # The build command

[[plugins]]
  package = "@netlify/plugin-nextjs" #because we are using Next-js
  [plugins.inputs]
    distDir = "out"  # Adjust based on your project settings

[dev]
  functions = "netlify/functions"  # The directory containing your serverless functions for local development

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
